### ISSUE TITLE
Is this app unable to  transfer udp?

### ISSUE THREAD

**Issue by qwased** [Mygod/VPNHotspot#1]
Still get a low NAT type (NAT D - could not receive udp)on my nintendo switch.But downloading and viewing website is ok.

**Comment by Mygod** [comment]
This app should work fine with UDP theoretically but I haven't tested it so
I'll look into that when possible.

However your case is slightly complicated. Could you share definitions of
NAT types for Nintendo Switch? I think Android uses UPnP for service
discovery under Wi-Fi direct mode so that could be a problem. This probably
could be fixed, but first could you test NAT types with this app under
native AP mode following theae directions:

1. You have to be on 0.1.0+ for this;
2. Turn on Hotspot in Android system; (not the one in app)
3. Turn on the main switch of this app;
4. Connect your Switch and see what's the connection type.

**Comment by qwased** [comment]
Tested the nat type of SSR,maybe it is causing the problem

![screenshot_2018-01-12-17-47-50-746_hu uszeged inf](https://user-images.githubusercontent.com/35343489/34869289-6204273e-f7c1-11e7-9c76-f9e3007f6571.png)
 This is turning off SSR and get NAT B (port restricted cone)

![screenshot_2018-01-12-17-47-07-031_hu uszeged inf](https://user-images.githubusercontent.com/35343489/34869396-bdfcd7c0-f7c1-11e7-90a6-9414ba9f0c74.png)
With SSR on my router,get a full cone

![screenshot_2018-01-12-17-44-34-141_hu uszeged inf](https://user-images.githubusercontent.com/35343489/34869433-d685c9b4-f7c1-11e7-83d5-44118e552df5.png)
But with SSR android,just become NAT D.Even though "tranfer UDP"selected in SSR, it seems not working.So setting  hotspot with SSR won't work either.

**Comment by Mygod** [comment]
I can verify that UDP forwarding isn't working. I'll fix it sometime.

**Comment by qwased** [comment]
Doing some research about android hotspot and figure out that android hotspot do not support UPNP so we can never get an open nat on it.Thanks for your work anyway

**Comment by Mygod** [comment]
Some further test shows that basic UDP forwarding actually is working. Maybe it has something to do with MTUs but I'm not sure. Let's keep this issue open for now.

**Comment by Mygod** [comment]
Seems like the problem on my side is just MTU. UDP seems to be working fine. Closing.
