### ISSUE TITLE
lt can't work well on oneplus 3t

### ISSUE THREAD

**Issue by fullstars** [Mygod/VPNHotspot#107]
然后我并不能在1+ 3t上面开启WiFi中继，错误代码 shell timeout. 这个软件需要两个物理网卡吗？但是我却找到了可以成功开启的shell脚本

Dear developers 
 When I open wireless repeater on 1+ 3t has a problem code  ''shell timeout'' . Does this application need two physical NICs? But I found a shell that can be successfully opened.The link is below
https://blog.omitol.com/2017/04/18/oneplus3-as-wifi-repeater/
https://developer.android.com/training/connect-devices-wirelessly/wifi-direct.html
I hope you can fix this issue,thank you .

**Comment by Mygod** [comment]
Root required.

**Comment by Mygod** [comment]
Did that solve your problem?

The article you posted is quite interesting and I will take a look later.

**Comment by Mygod** [comment]
So it seems like [it is possible to do the Linux way for Wi-Fi repeater](https://android.stackexchange.com/a/202336/181631). However, given that #31 has been fixed in Android 10, I don't think there is any reason to use the Linux way over the Android way except for Android 9-. If anyone is looking into this, feel free to implement it and submit a PR. 😄
