### ISSUE TITLE
[Feature] Port forwarding

### ISSUE THREAD

**Issue by Mygod** [Mygod/VPNHotspot#135]

**Comment by fangguihua** [comment]
这个功能要如何使用呢？

**Comment by ForestJohnson** [comment]
I am interested in this, perhaps also a SOCKS5 proxy feature would be awesome!!  

So that others connected to the VPNHotspot Android device via system tethering can reach out to the internet thru the VPN, [without requiring root on the phone](https://github.com/Mygod/VPNHotspot/issues/62)

I need this for hosting a server via the phone's LTE connection, so I will probably end up building my own separate proxy app or building in this feature on my own fork of Mygod/VPNHotspot

Excellent work with the app by the way!! Cheers!!

**Comment by Mygod** [comment]
I guess you can already do this with a port forwarding app without root.

**Comment by ForestJohnson** [comment]
I made a SOCKS5 proxy application for android which suits my needs. 

https://git.sequentialread.com/forest/android-socks5-proxy

https://github.com/sequentialread/AndroidSocks5Proxy
