### ISSUE TITLE
Add option to hide MAC address display in advice list

### ISSUE THREAD

**Issue by MarkussLugia** [Mygod/VPNHotspot#138]

**Comment by Mygod** [comment]
Why?

**Comment by MarkussLugia** [comment]
I often show the device list to classmates and friends, and as far as I know mac address is device-unique so I somehow feel it's not safe to share it to everyone (or please tell me it is safe because I really don't know much in network security stuff, thanks!).

**Comment by chevyfollowtooclose** [comment]
MAC address is only a vulnerability if someone is on your network already, they could pose as your router and intercept traffic. If they're on your network they already have access to your MAC address because devices on your network need to be discoverable in order to communicate.  They could just ping all devices on the network with /ipconfig to find the MAC and local IP addresses.

**Comment by Mygod** [comment]
Use a screenshot editor if you worry about that kind of information leaks.
