### ISSUE TITLE
[Discussion] AdBlock over VPN

### ISSUE THREAD

**Issue by M86xKC** [Mygod/VPNHotspot#139]
What are the 'dummy' vpns (adblock over vpn) that you tested with the app and worked?

I have tested many and none of them work!

Can you please give some hints?

Thanks

**Comment by Mygod** [comment]
https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker
https://github.com/blokadaorg/blokada

Not sure if these would work with bypassing tethering limits but try them out!

**Comment by M86xKC** [comment]
The first one does not use VPN API it only works with Samsung & Yandex browser.

I tried blokada, couldn't get it to work. I tried many others but no chance.

NetGuard works but there many are network drops unfortunately

**Comment by Mygod** [comment]
I remember you can make the first one use VPN by tweaking settings. What do you mean exactly by not working? What are your network provider's restrictions on tethering?

**Comment by M86xKC** [comment]
> What do you mean exactly by not working?

I can't access the internet with hotspot.

But when I use a proper vpn I can using VPNHotspot

**Comment by jmacul2** [comment]
1.1.1.1 - https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone
DNS66 (Fdroid)

Both of these work great for me.  If using 1.1.1.1, make sure you are just using DNS and NOT warp.

**Comment by Mygod** [comment]
Alright I did a little testing. It turns out that [this VPN version of AdGuard](https://adguard.com/en/adguard-android/overview.html) works but not Blokada. This is because Blokada basically works by set up a separate DNS server only so all traffic are still routed directly.

I could set up some diagnosis option to help you find which adblocking VPN would work.

**Comment by Mygod** [comment]
Please try v2.7.0. Go into settings and you should see the upstreams listed in "Current upstreams". If the primary/VPN upstream is displayed in bold, it should be good for bypassing tethering limitations.

**Comment by linuxandria** [comment]
AdGuard VPN works great with VPN tether, blokada does too but ONLY with it's built in (paid) VPN turned on (which slows the connection whereas AdGuard doesn't).
I'm using DNS over TLS with AdGuard (set up in app) so that may help

**Comment by worstperson** [comment]
AdGuard and AdClear both well as full local VPN implementations. 1.1.1.1 did not work for me unless Warp is enabled, and I found the WireGuard app to be more consistent for that. Host blockers seem to only implement enough to forge DNS responses, so they usually don't work either.

**Comment by puertajulian** [comment]
Versión 6.6 of 1.1.1.1 bring leaks in my case. Just if you have time to check.  Had to revert to 6.5 for it to stop leaking.

**Comment by SuspectTyrannosaurus** [comment]
Thank you @puertajulian for mentioning your trouble with Cloudflare / 1.1.1.1.

My hotspot stopped working (clients could connect but not access the internet), but reverting to version 6.5 of the 1.1.1.1 app (which I got from apkmirror) fixed it.

Neither version 6.6 nor 6.7 of "1.1.1.1" worked for me.

**Comment by worstperson** [comment]
Not an issue with VPNHotspot. If you have issues with 1.1.1.1 I suggest generating a profile with wgcf and importing it into the official Wireguard app. 
https://github.com/ViRb3/wgcf
https://play.google.com/store/apps/details?id=com.wireguard.android&hl=en_US&gl=US
Doing this let's me leave it as an always-on VPN without any network interruptions. Paid Warp+ will disconnect every 24hrs due to an unsupported feature(afaict) though.

**Comment by Mygod** [comment]
I am converting this issue to a discussion given the interest. 😉
