### ISSUE TITLE
Android 9 pie compatibility ?

### ISSUE THREAD

**Issue by pupyc** [Mygod/VPNHotspot#46]
Hi there

I'm on android pie now,
If I route the connection through the pre-configured system hotspot into the VPN Hotspot app it does not load anything in the computer connected, but dns works fine. weird ?

but when I create a temporary hotspot directly in the app the connection works and everything load from the connected computer.

when I was on android 8.1 I'm pretty sure it all worked just fine, but I really don't know what is the issue causing this !

**Comment by FebruaryVey** [comment]
I also have the same problem and i'm also on Android pie.

When i create the pre-configured system hotspot,it will show a interface that “Modify the prompt”.While i create atemporary hotspot  it won't show anything and work well.So i think they maybe worked via different ways.

Because the problem exsists,i should type the temporary password every time.😂

hope the author to have times and energy to solve this problem!

**Comment by Mygod** [comment]
Hey, thanks everyone for the support.

> hope the author to have times and energy to solve this problem!

Just a quick announcement that I'm currently occupied with other work ([more about this at XDA](https://forum.xda-developers.com/android/apps-games/app-vpn-hotspot-vpn-tethering-wi-fi-t3741604/post78262768)). I'll get back to these issues when I got time.

Just for a quick update, this app is tested thoroughly on Android Pie, in fact I'm using it on a daily basis on an Android 9 phone, so it's probably not caused by incompatibilities with Android 9.

@pupyc Thanks for the very nice comments. Please attach debug information.

@FebruaryVey I believe you are talking about an entirely unrelated issue. Please open a separate issue to elaborate on your issue. Also does turning on system hotspots via system's UI show you that interface as well?

**Comment by pupyc** [comment]
I've installed a clean installation of pie.
took some logs: https://paste.ubuntu.com/p/FdDrjYSTbg
also I did not change any default configuration in the app settings.
I'm using the [OpenVPN for Android](https://play.google.com/store/apps/details?id=de.blinkt.openvpn)

**Comment by pupyc** [comment]
@Mygod what **client**  are you using on your Android phone for the VPN? (OpenVPN for android, me)

and can you please send settings configuration, so I can make sure that it is not a problem with my configuration?

**Comment by Mygod** [comment]
I believe I have tested both OpenVPN (de.blinkt.openvpn) and Shadowsocks (com.github.shadowsocks). And based on stats from Google Play, >1k users are using this on Android 9 (more than people using it on 7.1) so I believe it is likely to be a device-specific issue.

Here's a brief documentation of all the settings:

## Upstream

* Upstream network interface: leave blank for auto detect. Put `none` to suppress tethering VPN. Put your interface name for tethering WireGuard.
* Fallback upstream: fallback is used when some VPN leave certain routes fallback to default network interface. Leave blank for auto detect. Put `none` to forbid falling back. Put other interface name if you feel like it.
* IP Masquerade: Source address/port from downstream packets will be remapped. Leave on if you don't know what it does. I find turning this option off sometimes works better for dummy VPNs like ad-blockers and socksifiers (like Shadowsocks). But you should never turn it off for real VPNs like OpenVPN, WireGuard, etc.

## Downstream

* Disable IPv6 tethering: Turning this option on will disable IPv6 for system tethering. Useful for stopping IPv6 leaks as this app currently doesn't handle IPv6 VPN tethering (see #6).
* Fallback DNS server[:port]: Only used when a DNS server isn't found on the tethered interface.
* Enable DHCP workaround: Only used if your device isn't able to get your clients IP addresses with VPN on.

**Comment by pupyc** [comment]
> so I believe it is likely to be a device-specific issue.
Me too, but don't know why it is working on oreo and not pie

**Comment by pupyc** [comment]
I've test another vpn app (orbot (tor)) just for the sake of testing, and it works fine,
but for some reason when I try to connect to my own VPN server through (OpenVPN for android) it does not work, also note that I've tested other servers along with mine,
but it seems the problem is the way I configure OpenVPN,
So I tried a fresh installation again and did not change any OpenVPN settings, and still it does not work!

 
So now my question is Do you use OpenVPN for android and a client for your VPN ?
if yes, can you please send me your particular configuration to duplicate it here and see if the issue still persists?

**Comment by pupyc** [comment]
after a little bit of tinkering with the options and toggles I found out that, this issue is cause by 
`Settings > System > Developer options > Networking (Section) > Disable "Tethering hardware acceleration"`

**Comment by Mygod** [comment]
This app should warn you if you have that option on. Did you see that warning before?

**Comment by pupyc** [comment]
@Mygod no

**Comment by Mygod** [comment]
Huh if you turn the option back on, can you see the warning in the app?

**Comment by pupyc** [comment]
@Mygod no _notification_ , no _warning_ .

**Comment by pupyc** [comment]
Hah I thought it was a pop-up or a pop over, will clear data and check again.

**Comment by Mygod** [comment]
Documentation in https://github.com/Mygod/VPNHotspot/issues/46#issuecomment-444358815 has been moved to [README](https://github.com/Mygod/VPNHotspot/blob/master/README.md#settings-and-how-to-use-them) and will be maintained there.
