### ISSUE TITLE
What changes exactly can this app do to my system? (and how to revert them)

### ISSUE THREAD

**Issue by TT44bb** [Mygod/VPNHotspot#8]
Question: What changes does this app make to the system which have any potential to stay permanently?

Reason for question: Pretty sure this app is the reason tethering doesn't work anymore on my phone (seems like DHCP is broken). Don't really want to do a full reset.
If you are interested, there are lots of
```
02-28 11:07:20.780 15842 15842 I dnsmasq : DHCPDISCOVER(rndis0) ce:2e:aa:44:45:46 
02-28 11:07:20.781 15842 15842 I dnsmasq : DHCPOFFER(rndis0) 192.168.42.83 ce:2e:aa:44:45:46
```
in logcat, but the client (which really is ce:2e:aa:44:45:46, I checked) never actually gets that IP.

**Comment by Mygod** [comment]
Changes to iptables and ip rules. They aren't permanent - you can always reboot to fully revert the effect. The clear button in settings in this app should revert the effect under normal circumstances as well.

This app has no effect on DHCP/dnsmasq. Have you tried other devices?

**Comment by TT44bb** [comment]
Thanks. :)
If I can fix the problem and then reproduce it, I'll file a proper bug report.

**Comment by Mygod** [comment]
A quick update. https://github.com/Mygod/VPNHotspot/issues/8#issuecomment-369395708 is no longer true since 1.2.0.

1. For (app version) 1.2 through 2.3 and 2.4+ on Android 9 and lower, there is one feature in the app that does permanent changes to your system: changing repeater credentials. This feature will modify `/data/misc/wifi/p2p_supplicant.conf` or `/data/vendor/wifi/wpa/p2p_supplicant.conf` for Android 9+. If things stopped working after you use this feature, simply delete this file and everything should start working again. However, as mentioned before, if you are using app version 2.4+ and have Android 10+ with safe mode on (or if you do not see this option), there will be no persisting changes made.
2. Since app v2.17.1 on Android 12 or higher, global setting `uids_allowed_on_restricted_networks` will be changed if you do not install this app as system app. See also: https://github.com/Mygod/VPNHotspot/blob/master/README.md#features-that-requires-system-app-installation
3. If you edited the system Wi-Fi hotspot configuration through this app, those changes will also persist. Undo those changes if you face any issues.

P.S. Just in case you are unsure, this app does not modify your system partition and will keep your systemless root systemless.

EDIT: This comment has been updated for 2.4 update and information about systemless root.

EDIT 2: Added information about safe mode.

EDIT 3: This is no longer maintained. The up-to-date information is now in README instead.

**Comment by Mygod** [comment]
@yqs112358 Hi this change will not break SafetyNet (just verified myself). Indeed this change could be done even on a non-rooted device through `adb shell settings` so I see no reason that this would be used for checking SN.
