### ISSUE TITLE
Feature Req: Auto-Tether On VPN Connect

### ISSUE THREAD

**Issue by WoWMage95** [Mygod/VPNHotspot#9]
Hello,

Sorry if wrong place but would love to request an option to automatically enable WiFi tether on VPN connect.  My VPN connection sometimes drops and then the hotspot leaks.

Option to start the app on boot would also be great!

**Comment by Mygod** [comment]
I'm not sure what you mean by automatically enabling Wi-Fi tether on VPN connect. Currently as long as you have turned on the switch in app, routing rules will be updated accordingly whenever your VPN goes up/down. Enabling strict mode introduced in 1.1 will prevent bypassing connections in repeater mode.

I also don't see why you want to start the app on boot unless you're using a dedicated Android device as a VPN router?

**Comment by Mygod** [comment]
Looks like several people uses this on their tv boxes. Might consider adding this sometime.

**Comment by Mygod** [comment]
MagiskSU doesn't seem to play nicely right after boot... Therefore I suggest toggling manually for now.

**Comment by sea3pea0** [comment]
How about the ability to control this app via intents so that we could use tasker to initiate actions in this app? I have an android head unit in my car that is connected to an android phone acting as a hotspot and running this app. 

The only way I've found to reliably avoid having my hotspot being throttled by t-mobile is to share the hotspot through a vpn connection. 

Right now, when my car is turned on or the android phone boots up, tasker turns my hotspot on and when the car turns off the hotspot is turned off by tasker. With tasker I sense whether the car is on or off by the charging cable for the phone. If its charging, the car is on and if not its off.

It would be great if I could also have an action to turn vpn hotspot on for my wlan as one of the actions. This way the process would be automated.

As of now, if the hotspot is turned off and then back on, I have to go manually into the vpn hotspot app and re-toggle the wlan switch to route the hotspot traffic back through the vpn.

Thanks in adavnce for your help and/or consideration for this feature request. Obviously if it was possible for this app to remember the last setting and just ensure that either after boot or if the hotspot is turned off and back on that traffic would be routed through the vpn, this would work for me too. If its easier to make this possible through the use of tasker automations perhaps this would help others too.
